agent:
  actor_type: disc
  algo: ppo
  layers:
  - 256
  - 256
  model_name: PPO_flat-ships-latent_flat_discount-0.7-new
  save_dir: models
env:
  action_space: flat
  board_height: 10
  board_width: 10
  latent_var_precision: 16
  max_steps: 1000
  ship_sizes:
  - 2
  - 3
  - 3
  - 4
  - 5
  state_space: flat-ships-latent
eval:
  eval_interval: 5
  num_ep: 5
  num_eval_after: 10
  seed: 2021
log_dir: runs/Dec05_165416_PPO_flat-ships-latent_flat_discount-0.7-new
logging:
  disabled: false
  log_base_dir: runs
  log_to_comet: false
resume: false
training:
  discount: 0.7
  gpu_idx: 0
  num_procs: 1
  ppo:
    actor_learning_rate: 0.0003
    actor_steps: 50
    clip_ratio: 0.2
    critic_learning_rate: 0.001
    critic_steps: 50
    entropy_coeff: 0.001
    gae_lam: 0.97
    target_kl: 0.015
  save_interval: 5
  seed: 42
  total_steps: 1000
  train_samples: 900
  use_gpu: false
